codecov:
  require_ci_to_pass: yes

comment:
  layout: "diff"
  behavior: once
  require_changes: true
  require_base: yes
  require_head: yes
  branches:
    - "main"

coverage:
  status:
    project:
      default: false
      tests:
        paths:
          - "tests/"
        target: 100%
      source:
        paths:
          - "sources"
        target: 90%
        threshold: 0.002
    patch:
      default:
        target: 80%