# flake8, black, pep8 test
name: Pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black flake8
        
    - name: black, flake8 test
      uses: wearerequired/lint-action@v1
      with:
        black: true
        flake8: true
        flake8_args: "--max-line-length=88 --ignore=conf.py"
        
#     - name: pep8 test
#       uses: peter-evans/autopep8@v1
#       with:
#         args: --recursive --in-place --aggressive --aggressive .
