name: Coverage and Test

on:
  - push
  - pull_request

jobs:
  cov-test:
    name: Coverage test
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
            - os: ubuntu-latest
            - os: windows-latest
        pyversion: [ 3.8, 3.9 ]

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        pip install -e file://$PWD/
        pip install codecov
        pip install pytest-cov parameterized
        pytest tests --cov=uetai/ --cov-report=xml

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
